routes/web.php
<?php

use App\Models\Role;


use App\Models\User;  //libre
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Mail\ContactanosMailable;   //libre
use Illuminate\Support\Facades\Gate; //libre
use App\Http\Controllers\Admin\RolController;
use Illuminate\Support\Facades\Mail;  //libre
use Illuminate\Support\Facades\Auth;// liberia
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Admin\TallaController;
use App\Http\Controllers\Admin\ImagenController;
use App\Http\Controllers\Admin\OfertaController;
use App\Http\Controllers\Admin\OrigenController;
use App\Http\Controllers\Cliente\CartController;
use App\Http\Controllers\Admin\SeccionController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\ArticuloController;
use App\Http\Controllers\Admin\ProductoController;
use App\Http\Controllers\Cliente\BuscarController;
use App\Http\Controllers\Cliente\PerfilController;
use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\PublicadoController;
use App\Http\Controllers\Cliente\DetalleController;
use App\Http\Controllers\Admin\TallaComboController;
use App\Http\Controllers\Cliente\AccionesController;
use App\Http\Controllers\Cliente\CatalogoController;
use App\Http\Controllers\Cliente\CheckoutController;
use App\Http\Controllers\Admin\MetodoAdminController;
use App\Http\Controllers\Admin\CrearUsuarioController;
use App\Http\Controllers\Admin\UserController; //libre
use App\Http\Controllers\HomeUserController;   //libre
use App\Http\Controllers\Admin\HomeController;  //libre
use App\Http\Controllers\Admin\Reporte_UsuatioController;
use App\Http\Controllers\Cliente\CorreoFacturaController;
use App\Http\Controllers\Cliente\MetodoClienteController;
use App\Http\Controllers\Cliente\OfertaDetalleController;
use App\Http\Controllers\Admin\Relaccion_ImagenController;
use App\Http\Controllers\Admin\ValidarPagoAdminController;
use App\Http\Controllers\Cliente\FacturaClienteController;
use App\Http\Controllers\Cliente\SinAuthController;
use App\Http\Controllers\Logistica\MetodoLogisticaController;
use App\Http\Controllers\Cliente\ValidarPagoClienteController;
use App\Http\Controllers\Repartidor\MetodoRepartidorController;
use App\Http\Controllers\Logistica\EntregarPedidoLogisticaController;
use App\Http\Controllers\Repartidor\EntregarPedidosMensajeroController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    //Ofertas


    $products=DB::table('productos')
    ->where('imagens.perfil','si')
    ->where('ofertas.estado','1')
    ->select(
        'productos.codigo_producto',
        'productos.id',
        'relaccion__imagens.relaccion_id',
        'productos.stock',
        'productos.estado',
        'ofertas.precio_oferta',
        'productos.descripcion',
        'imagens.url as imagen',
        'articulos.descripcion as articulo',
        'categorias.descripcion as categoria',
        'productos.created_at',
        'imagens.perfil',
        'imagens.url'
    )
    ->join('ofertas', 'productos.id', '=', 'ofertas.producto_id')
    ->join('publicados', 'productos.id', '=', 'publicados.producto_id')
    ->join('relaccions', 'productos.relaccion_id', '=', 'relaccions.id')
    ->join('articulos', 'relaccions.articulo_id', '=', 'articulos.id')
    ->join('categorias', 'relaccions.categoria_id', '=', 'categorias.id')
    ->join('relaccion__imagens', 'relaccions.id', '=', 'relaccion__imagens.relaccion_id')
    ->join('imagens', 'relaccion__imagens.imagen_id', '=', 'imagens.id')
    ->get();



  //  return $products;

    return view('welcome')->with(['products' =>$products]);
});


Route::get('/cart', [CartController::class, 'cart'])->name('cart.index');
Route::post('/add', [CartController::class, 'add'])->name('cart.store');
Route::post('/update', [CartController::class, 'update'])->name('cart.update');
Route::post('/remove', [CartController::class, 'remove'])->name('cart.remove');
Route::post('/clear', [CartController::class, 'clear'])->name('cart.clear');

Auth::routes(['verify' =>true]);



Route::post('/combo', [TallaComboController::class, 'consultaTallas']);
Route::get('/estadouser/{id}/{state}/{name}', [TallaComboController::class, 'usuarioEstado']);
Route::get('/estadocategoria/{id}/{estado}/{descripcion}', [TallaComboController::class, 'categoriaEstado']);
Route::get('/estadocolor/{id}/{estado}/{descripcion}', [TallaComboController::class, 'colorEstado']);
Route::get('/estadoseccion/{id}/{estado}/{descripcion}', [TallaComboController::class, 'seccionEstado']);
Route::get('/estadotalla/{id}/{estado}/{talla}', [TallaComboController::class, 'tallaEstado']);
Route::get('/estadoorigen/{id}/{estado}/{descripcion}', [TallaComboController::class, 'origenEstado']);
Route::get('/publicar/{producto_id}/{relaccion_id}', [TallaComboController::class, 'publicarProducto']);
Route::get('/publicarestado/{id}/{estado}', [TallaComboController::class, 'estadoPublicado']);
Route::get('/ofertar/{producto_id}/{publicado_id}', [TallaComboController::class, 'ofertarProducto']);
Route::get('/ofertaestado/{id}/{estado}', [TallaComboController::class, 'estadoOferta']);
Route::get('/eliminaroferta/{id}/{idpublicado}', [TallaComboController::class, 'eliminarOferta']);




Route::get('/tienda', [HomeUserController::class, 'getUser'])->name('tienda');
Route::post('/combocatalogo', [HomeUserController::class, 'catalogo'])->name('combocatalogo');

/*
Route::get('/contactanos', function () {
    $correo = new ContactanosMailable;
    Mail::to('bacoth@gmail.com')->send($correo);

    return "Mensaje enviado";
});
*/

//Route::get('/enviar/factura',[CorreoFacturaController::class, 'envioFactura'])->name('envio.factura');


Route::resource('/role', RoleController::class)->names('role');


//Route::get('/cliente/perfil',[ RegisterController::class, 'actualizar'])->name('cliente-perfil');


Route::get('/test', function () {

	return Role::create([
        'rol' => 'Logistica',
        'slug' => 'logistica',
        'description' =>'Entregar productos',
        'full-access' =>'no'
        ]);

    });


// Google login
Route::get('login/google', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('login/google/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGoogleCallback']);

// FaceBook login
Route::get('login/facebook', [App\Http\Controllers\Auth\LoginController::class, 'redirectToFacebook'])->name('login.facebook');
Route::get('login/facebook/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleFacebookCallback']);

// GitHub login
Route::get('login/github', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGithub'])->name('login.github');
Route::get('login/github/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGithubCallback']);


//Controlladores para Admin
Route::prefix('/administrador')->group(function (){
    Route::resource('/perfil', UserController::class)->names('perfil');
    Route::resource('/modulo_producto/producto', ProductoController::class)->names('producto');
    Route::resource('/modulo_producto/gestion/color', ColorController::class)->names('color');
    Route::resource('/modulo_producto/gestion/categoria', CategoriaController::class)->names('categoria');
    Route::resource('/modulo_producto/gestion/seccion', SeccionController::class)->names('seccion');
    Route::resource('/modulo_producto/gestion/talla', TallaController::class)->names('talla');
    Route::resource('/modulo_producto/gestion/origen', OrigenController::class)->names('origen');
    Route::resource('/modulo_producto/gestion/articulo', ArticuloController::class)->names('articulo');
    Route::resource('/modulo_producto/publicado/publicado', PublicadoController::class)->names('publicado');
    Route::resource('/modulo_producto/publicado/oferta', OfertaController::class)->names('oferta');
    Route::resource('/modulo_producto/producto/imagen', ImagenController::class)->names('imagen');
    Route::resource('/modulo_producto/producto/relaccion_imagen', Relaccion_ImagenController::class)->names('relaccion_imagen');
    Route::get('modulo_usuario/reporte_usuario',[Reporte_UsuatioController::class, 'reporteUsuario'])->name('reporte_usuario');
    Route::get('modulo_usuario/reporte_cliente',[Reporte_UsuatioController::class, 'reporteCliente'])->name('reporte_cliente');
    Route::resource('/modulo_usuario/rol', RolController::class)->names('asignarRol');
    Route::resource('/modulo_usuario/crear', CrearUsuarioController::class)->names('crearusuario');
    Route::get('/panel',[HomeController::class,'index'])->name('home');
    Route::resource('/facturacion/validar/pago', ValidarPagoAdminController::class)->names('validar.pago.admin');
    Route::get('/pago/rechazado/{id}', [MetodoAdminController::class, 'rechazadoPago']);
    Route::get('/pago/factura/detalle/{id}', [MetodoAdminController::class, 'detalleFacturaAdmin']);
    Route::get('/facturacion/generar/factura', [MetodoAdminController::class, 'facturaPendiente']);
    Route::get('/facturacion/factura/autorizado', [MetodoAdminController::class, 'facturaAutorizado']);
    Route::get('/facturacion/factura/rechazado', [MetodoAdminController::class, 'facturaRechazado']);
    Route::get('/facturacion/factura/facturaPDF/{id}', [MetodoAdminController::class, 'descargarPDF']);
    Route::get('/reportes/entregas', [MetodoAdminController::class, 'reporteEntregas']);
    Route::get('/facturacion/generar/factura/{id}', [MetodoAdminController::class, 'generarNumerador']);

app/Http/Controllers/Cliente/PerfilController.php
<?php

namespace App\Http\Controllers\Cliente;

use App\Models\User;
use Image; //libreria
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Auth;// liberia

class PerfilController extends Controller
{


 /**
     * Create a new controller instance.
     *
     * @return void
     */

    public function __construct()
    {
        $this->middleware(['auth','verified']);
        $this->middleware('cliente',['only'=>['index', 'create', 'store', 'show', 'update', 'destroy']]);

    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $users = auth::user();
      $email = $users['email'];
      $users=User::where('users.email', $email)
      ->get();
  return view('page/cliente/perfil/index', compact('users'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $iduser =  Crypt::decrypt($id);

        $users=User::where('id', $iduser)
        ->get();


        return view('page/cliente/perfil/editar', compact('users','iduser'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'nombre'   => 'required|min:3|max:50',
            'apellido'   => 'required|min:3|max:50',
            'celular'   => 'required|min:3|max:50',
            'direccion'   => 'required|min:3|max:200',
            'imagen'  => '|file|max:1024|mimes:jpeg,bmp,png,jpg',
            /*
            'password' =>  ['required', 'string', 'min:4'],
            */

        ]);
        $url=null;
        if($request->hasfile('imagen')){
            $avatar = $request->file('imagen');
            $filename = Str::random(12) . '.' . $avatar->getClientOriginalExtension();
               Image::make($avatar)->resize(300, 300)->save( public_path('images\perfil\\' . $filename) );
               $url= '\images\perfil\\' . $filename;
            }

        $user = User::findOrFail($id);
        $image_path = public_path().$user->avatar;
        $user->id = $id;
        $user->name = $request->nombre;
        $user->surname = $request->apellido;

        $user->phone = $request->celular;
        $user->city = $request->direccion;
    //    $user->password = Hash::make($request->password);
        if($request->hasfile('imagen')){
            if(($user->avatar=='\images\perfil\1.png')||($user->avatar=='\images\perfil\2.jpg')){
                $user->avatar =$url;
            }else{
                unlink($image_path);
                $user->avatar =$url;

            }


        }
        $user->update();
        $users = auth::user();
        $email = $users['email'];
        $users=User::where('users.email', $email)
        ->get();
        return redirect()->route('cliente-perfil.index')
        ->with('status_success', 'Perfil actualizado con éxito ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/page/admin/perfil/editar.blade.php
@extends('adminlte::page')
@section('title', 'Perfil')

@section('plugins.Sweetalert2', false)
@section('content_header')

@stop

@section('content')

<div class="card">
    <div class="card-header">
    <h1 class="card-title">Edital Perfil</h1>
    </div>
    <div class="card-body">
        @include('custom.message')
        <form action="{{ route('perfil.update', $iduser)}}" method="POST" enctype="multipart/form-data">
            @method('Put')
            @csrf
            <div class="container rounded bg-white mt-5 mb-5">
                <div class="row">
                    <div class="col-md-5 border-right">
                        @foreach ($users as $user  )
                        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                            @if ($user->avatar=="null")
                            <img class="rounded-circle mt-5" width="150px"
                            src="\images\perfil\no.jpg">
                            <input accept="image/png,image/jpeg" type="file" name="imagen" id="imagen" >
                            @else
                            <img class="rounded-circle mt-5" width="150px"
                            src="{{$user->avatar}}">
                            <span>
                                <input accept="image/png,image/jpeg" type="file" name="imagen" id="imagen" >
                            </span>
                            @endif
                            <span class="font-weight-bold">{{$user->name}}</span>
                            <span class="text-black-50">{{$user->email}}</span>
                            <div class="mt-5 text-center">
                                <center>      <input class="btn btn-primary" type="submit" value="Guardar"\></center>

                            </div>
                            <span> </span></div>

                    </div>
                    <div class="col-md-7 border-right">
                        <div class="p-3 py-5">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h4 class="text-right">Configuración de perfil</h4>
                            </div>
                            <div class="row mt-2">
                                <div class="col-md-6"><label class="labels">Nombres</label><input type="text" class="form-control" name="nombre" id="nombre" placeholder="Nombres" value="{{$user->name}}" ></div>
                                <div class="col-md-6"><label class="labels">Apellidos</label><input type="text" class="form-control" name="apellido" id="apellido" value="{{$user->surname}}" placeholder="Apellidos" ></div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-md-12"><label class="labels">Correo Electrónico</label><input type="text" class="form-control" name="correo" id="correo" placeholder="Correo" value="{{$user->email}}" readonly></div>
                                <div class="col-md-12"><label class="labels">Cédula de Identidad</label><input type="text" class="form-control" name="cedula" id="cedula" placeholder="Cédula" value="{{$user->idcard}}" readonly></div>
                                <div class="col-md-12"><label class="labels">Telefono</label><input type="text" class="form-control" placeholder="Telefono" name="celular" id="celular" value="{{$user->phone}}"></div>
                                <div class="col-md-12"><label class="labels">Dirección</label><input type="text" class="form-control" placeholder="Dirección" name="direccion" id="direccion" value="{{$user->city}}"></div>
                                <div class="col-md-12"><label class="labels"></label>
                                 <br>
                                <a class="btn btn-outline-primary" href="{{ url('password/reset')}}">Cambiar Contraseña:</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            @endforeach


  </div>
</form>

@stop

@section('css')
	<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
Swal.fire(
  'Good job!',
  'You clicked the button!',
  'success'
)
</script>
@stop

resources/views/page/admin/perfil/index.blade.php
@extends('adminlte::page')
@section('title', 'Perfil')

@section('plugins.Sweetalert2', false)
@section('content_header')

@stop

@section('content')
@foreach ($users as $user  )
<div class="card">
        <div class="card-header">Perfil {{$user->name}}</div>


        @include('custom.message')
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row">
                <div class="col-md-5 border-right">

                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                        @if ($user->avatar=="null")
                        <img class="rounded-circle mt-5" width="150px"
                        src="\images\perfil\no.jpg">
                        @else
                        <img class="rounded-circle mt-5" width="150px"
                        src="{{$user->avatar}}">
                        @endif
                        <span class="font-weight-bold">{{$user->name}}</span>
                        <span class="text-black-50">{{$user->email}}</span>
                        <div class="mt-5 text-center">
                            <center>
                                <a class="btn btn-success"  href="{{ route('perfil.edit',Crypt::encrypt($user->id))}}">Editar</a>
                                </center>
                        </div>
                        <span> </span></div>

                </div>
                <div class="col-md-7 border-right">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Configuración de perfil</h4>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-6"><label class="labels">Nombres</label>  <input type="text" class="form-control" placeholder="Nombres" value="{{$user->name}}" readonly></div>
                            <div class="col-md-6"><label class="labels">Apellidos</label><input type="text" class="form-control" placeholder="Apellidos" value="{{$user->surname}}" readonly></div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-12"><label class="labels">Correo Electrónico</label><input type="text" class="form-control" placeholder="" value="{{$user->email}}" readonly></div>
                            <div class="col-md-12"><label class="labels">Cédula de Identidad</label><input type="text" class="form-control" placeholder="" value="{{$user->idcard}}" readonly></div>
                            <div class="col-md-12"><label class="labels">Telefono</label><input type="text" class="form-control" placeholder="Telefono" value="{{$user->phone}}" readonly></div>

                            <div class="col-md-12"><label class="labels">Dirección</label><input type="text" class="form-control" placeholder="Dirección" value="{{$user->city}}" readonly></div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
        @endforeach
    </form>
  </div>


@stop

@section('css')
	<link rel="stylesheet" href="/css/admin_cusertom.css">
@stop

@section('js')
<script>
Swal.fire(
  'Good job!',
  'You clicked the button!',
  'success'
)
</script>
@stop