routes/web.php
<?php

use App\Models\Role;


use App\Models\User;  //libre
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Mail\ContactanosMailable;   //libre
use Illuminate\Support\Facades\Gate; //libre
use App\Http\Controllers\Admin\RolController;
use Illuminate\Support\Facades\Mail;  //libre
use Illuminate\Support\Facades\Auth;// liberia
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Admin\TallaController;
use App\Http\Controllers\Admin\ImagenController;
use App\Http\Controllers\Admin\OfertaController;
use App\Http\Controllers\Admin\OrigenController;
use App\Http\Controllers\Cliente\CartController;
use App\Http\Controllers\Admin\SeccionController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\ArticuloController;
use App\Http\Controllers\Admin\ProductoController;
use App\Http\Controllers\Cliente\BuscarController;
use App\Http\Controllers\Cliente\PerfilController;
use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\PublicadoController;
use App\Http\Controllers\Cliente\DetalleController;
use App\Http\Controllers\Admin\TallaComboController;
use App\Http\Controllers\Cliente\AccionesController;
use App\Http\Controllers\Cliente\CatalogoController;
use App\Http\Controllers\Cliente\CheckoutController;
use App\Http\Controllers\Admin\MetodoAdminController;
use App\Http\Controllers\Admin\CrearUsuarioController;
use App\Http\Controllers\Admin\UserController; //libre
use App\Http\Controllers\HomeUserController;   //libre
use App\Http\Controllers\Admin\HomeController;  //libre
use App\Http\Controllers\Admin\Reporte_UsuatioController;
use App\Http\Controllers\Cliente\CorreoFacturaController;
use App\Http\Controllers\Cliente\MetodoClienteController;
use App\Http\Controllers\Cliente\OfertaDetalleController;
use App\Http\Controllers\Admin\Relaccion_ImagenController;
use App\Http\Controllers\Admin\ValidarPagoAdminController;
use App\Http\Controllers\Cliente\FacturaClienteController;
use App\Http\Controllers\Cliente\SinAuthController;
use App\Http\Controllers\Logistica\MetodoLogisticaController;
use App\Http\Controllers\Cliente\ValidarPagoClienteController;
use App\Http\Controllers\Repartidor\MetodoRepartidorController;
use App\Http\Controllers\Logistica\EntregarPedidoLogisticaController;
use App\Http\Controllers\Repartidor\EntregarPedidosMensajeroController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    //Ofertas


    $products=DB::table('productos')
    ->where('imagens.perfil','si')
    ->where('ofertas.estado','1')
    ->select(
        'productos.codigo_producto',
        'productos.id',
        'relaccion__imagens.relaccion_id',
        'productos.stock',
        'productos.estado',
        'ofertas.precio_oferta',
        'productos.descripcion',
        'imagens.url as imagen',
        'articulos.descripcion as articulo',
        'categorias.descripcion as categoria',
        'productos.created_at',
        'imagens.perfil',
        'imagens.url'
    )
    ->join('ofertas', 'productos.id', '=', 'ofertas.producto_id')
    ->join('publicados', 'productos.id', '=', 'publicados.producto_id')
    ->join('relaccions', 'productos.relaccion_id', '=', 'relaccions.id')
    ->join('articulos', 'relaccions.articulo_id', '=', 'articulos.id')
    ->join('categorias', 'relaccions.categoria_id', '=', 'categorias.id')
    ->join('relaccion__imagens', 'relaccions.id', '=', 'relaccion__imagens.relaccion_id')
    ->join('imagens', 'relaccion__imagens.imagen_id', '=', 'imagens.id')
    ->get();



  //  return $products;

    return view('welcome')->with(['products' =>$products]);
});


Route::get('/cart', [CartController::class, 'cart'])->name('cart.index');
Route::post('/add', [CartController::class, 'add'])->name('cart.store');
Route::post('/update', [CartController::class, 'update'])->name('cart.update');
Route::post('/remove', [CartController::class, 'remove'])->name('cart.remove');
Route::post('/clear', [CartController::class, 'clear'])->name('cart.clear');

Auth::routes(['verify' =>true]);



Route::post('/combo', [TallaComboController::class, 'consultaTallas']);
Route::get('/estadouser/{id}/{state}/{name}', [TallaComboController::class, 'usuarioEstado']);
Route::get('/estadocategoria/{id}/{estado}/{descripcion}', [TallaComboController::class, 'categoriaEstado']);
Route::get('/estadocolor/{id}/{estado}/{descripcion}', [TallaComboController::class, 'colorEstado']);
Route::get('/estadoseccion/{id}/{estado}/{descripcion}', [TallaComboController::class, 'seccionEstado']);
Route::get('/estadotalla/{id}/{estado}/{talla}', [TallaComboController::class, 'tallaEstado']);
Route::get('/estadoorigen/{id}/{estado}/{descripcion}', [TallaComboController::class, 'origenEstado']);
Route::get('/publicar/{producto_id}/{relaccion_id}', [TallaComboController::class, 'publicarProducto']);
Route::get('/publicarestado/{id}/{estado}', [TallaComboController::class, 'estadoPublicado']);
Route::get('/ofertar/{producto_id}/{publicado_id}', [TallaComboController::class, 'ofertarProducto']);
Route::get('/ofertaestado/{id}/{estado}', [TallaComboController::class, 'estadoOferta']);
Route::get('/eliminaroferta/{id}/{idpublicado}', [TallaComboController::class, 'eliminarOferta']);




Route::get('/tienda', [HomeUserController::class, 'getUser'])->name('tienda');
Route::post('/combocatalogo', [HomeUserController::class, 'catalogo'])->name('combocatalogo');

/*
Route::get('/contactanos', function () {
    $correo = new ContactanosMailable;
    Mail::to('bacoth@gmail.com')->send($correo);

    return "Mensaje enviado";
});
*/

//Route::get('/enviar/factura',[CorreoFacturaController::class, 'envioFactura'])->name('envio.factura');


Route::resource('/role', RoleController::class)->names('role');


//Route::get('/cliente/perfil',[ RegisterController::class, 'actualizar'])->name('cliente-perfil');


Route::get('/test', function () {

	return Role::create([
        'rol' => 'Logistica',
        'slug' => 'logistica',
        'description' =>'Entregar productos',
        'full-access' =>'no'
        ]);

    });


// Google login
Route::get('login/google', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('login/google/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGoogleCallback']);

// FaceBook login
Route::get('login/facebook', [App\Http\Controllers\Auth\LoginController::class, 'redirectToFacebook'])->name('login.facebook');
Route::get('login/facebook/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleFacebookCallback']);

// GitHub login
Route::get('login/github', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGithub'])->name('login.github');
Route::get('login/github/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGithubCallback']);


//Controlladores para Admin
Route::prefix('/administrador')->group(function (){
    Route::resource('/perfil', UserController::class)->names('perfil');
    Route::resource('/modulo_producto/producto', ProductoController::class)->names('producto');
    Route::resource('/modulo_producto/gestion/color', ColorController::class)->names('color');
    Route::resource('/modulo_producto/gestion/categoria', CategoriaController::class)->names('categoria');
    Route::resource('/modulo_producto/gestion/seccion', SeccionController::class)->names('seccion');
    Route::resource('/modulo_producto/gestion/talla', TallaController::class)->names('talla');
    Route::resource('/modulo_producto/gestion/origen', OrigenController::class)->names('origen');
    Route::resource('/modulo_producto/gestion/articulo', ArticuloController::class)->names('articulo');
    Route::resource('/modulo_producto/publicado/publicado', PublicadoController::class)->names('publicado');
    Route::resource('/modulo_producto/publicado/oferta', OfertaController::class)->names('oferta');
    Route::resource('/modulo_producto/producto/imagen', ImagenController::class)->names('imagen');
    Route::resource('/modulo_producto/producto/relaccion_imagen', Relaccion_ImagenController::class)->names('relaccion_imagen');
    Route::get('modulo_usuario/reporte_usuario',[Reporte_UsuatioController::class, 'reporteUsuario'])->name('reporte_usuario');
    Route::get('modulo_usuario/reporte_cliente',[Reporte_UsuatioController::class, 'reporteCliente'])->name('reporte_cliente');
    Route::resource('/modulo_usuario/rol', RolController::class)->names('asignarRol');
    Route::resource('/modulo_usuario/crear', CrearUsuarioController::class)->names('crearusuario');
    Route::get('/panel',[HomeController::class,'index'])->name('home');
    Route::resource('/facturacion/validar/pago', ValidarPagoAdminController::class)->names('validar.pago.admin');
    Route::get('/pago/rechazado/{id}', [MetodoAdminController::class, 'rechazadoPago']);
    Route::get('/pago/factura/detalle/{id}', [MetodoAdminController::class, 'detalleFacturaAdmin']);
    Route::get('/facturacion/generar/factura', [MetodoAdminController::class, 'facturaPendiente']);
    Route::get('/facturacion/factura/autorizado', [MetodoAdminController::class, 'facturaAutorizado']);
    Route::get('/facturacion/factura/rechazado', [MetodoAdminController::class, 'facturaRechazado']);
    Route::get('/facturacion/factura/facturaPDF/{id}', [MetodoAdminController::class, 'descargarPDF']);
    Route::get('/reportes/entregas', [MetodoAdminController::class, 'reporteEntregas']);
    Route::get('/facturacion/generar/factura/{id}', [MetodoAdminController::class, 'generarNumerador']);

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $primaryKey = 'id';
    protected $fillable =[
        'rol', 'slug', 'description','full-access',
        ];


    public function users(){
      return $this->belongsToMany('App\User')->withTimesTamps();
           }

    public function permissions(){
            return $this->belongsToMany('App\Models\Permission')->withTimesTamps();
        }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\Cantone;
use App\Models\Factura;
use App\Models\Producto;
use App\Models\Parroquia;
use App\Models\Provincia;
use App\Models\Permission;
use App\Models\Numeradores;
use App\Models\ValidarPago;
use Illuminate\Support\Str;
use App\Models\Metodo_Envio;
use Illuminate\Http\Request;
use App\Models\Detalle_Factura;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Response;
use App\Models\DatosFacturacionElectronica;
use Illuminate\Support\Facades\Gate; //libre



class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */



    public function validar_clave($clave)
    {



        if ($clave == "") {
            $verificado = false;
            return $verificado;
        }

        $x = 2;
        $sumatoria = 0;
        for ($i = strlen($clave) - 1; $i >= 0; $i--) {
            if ($x > 7) {
                $x = 2;
            }
            $sumatoria = $sumatoria + ($clave[$i] * $x);
            $x++;
        }
        $digito = $sumatoria % 11;
        $digito = 11 - $digito;

        switch ($digito) {
            case 10:
                $digito = "1";
                break;
            case 11:
                $digito = "0";
                break;
        }

        /*
      if (strtolower($digito_v)==$digito){
      $verificado=true;
      } else {
      $verificado=false;
      }

     */

        return $digito;
    }



    public function index()
    {
/*
        select *from parroquias
where provincia_id =17
AND canton_id=5;

*/
        $parroquias=DB::table('cantones')
        ->where('cantones.canton_id',2)
        ->where('cantones.provincia_id',17)
        ->get();

        return $parroquias;




        /*

      //  Gate::authorize('haveaccess','role.index');
        $roles =  Role::orderBy('id','Asc')->paginate(2);
         // $roles = Role::get();
        return view('role.index',compact('roles'));
*/
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('haveaccess', 'role.create');
        $permissions = Permission::get();

        return view('role.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('haveaccess', 'role.create');
        $request->validate([
            'name'          => 'required|max:50|unique:roles,name',
            'slug'          => 'required|max:50|unique:roles,slug',
            'full-access'   => 'required|in:yes,no'
        ]);

        $role = Role::create($request->all());

        //    if ($request->get('permission')){
        $role->permissions()->sync($request->get('permission'));
        //}
        return redirect()->route('role.index')
            ->with('status_success', 'Role saved successfully ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        Gate::authorize('haveaccess', 'role.show');
        $permission_role = [];

        foreach ($role->permissions as $permission) {
            $permission_role[] = $permission->id;
        }
        //return   $permission_role;


        //return $role;
        $permissions = Permission::get();




        return view('role.view', compact('permissions', 'role', 'permission_role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        Gate::authorize('haveaccess', 'role.edit');
        $permission_role = [];
        foreach ($role->permissions as $permission) {

            $permission_role[] = $permission->id;
        }
        //return $permission_role;
        $permissions = Permission::get();
        return view('role.edit', compact('permissions', 'role', 'permission_role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        Gate::authorize('haveaccess', 'role.edit');
        $request->validate([
            'name'          => 'required|max:50|unique:roles,name,' . $role->id,
            'slug'          => 'required|max:50|unique:roles,slug,' . $role->id,
            'full-access'   => 'required|in:yes,no'
        ]);

        $role->update($request->all());

        //   if ($request->get('permission')) {
        //return $request->all();
        $role->permissions()->sync($request->get('permission'));
        //  }
        return redirect()->route('role.index')
            ->with('status_success', 'Role updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        Gate::authorize('haveaccess', 'role.delete');
        $role->delete();

        return redirect()->route('role.index')
            ->with('status_success', 'Role successfully removed');
    }
}

resources/views/role/create.blade.php
@extends('layouts.master.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Roles') }}</div>

                <div class="card-body">
                   @include('custom.message')

                        <form action="{{ route('role.store')}}" method="POST">
                        @csrf
                        <div class="container">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="name" placeholder="Name" name="name"   value={{old('name')}}>
                              </div>
                              <div class="mb-3">
                                <input type="text" class="form-control" id="slug" placeholder="Slug" name="slug" value={{old('slug')}}>
                              </div>
                              <div class="form-floating">
                                <textarea class="form-control" placeholder="Description" id="description" name="description" style="height: 100px" >{{ old('description')}}</textarea>
                              </div>
                        </div>
                        <hr>
                        <h3>Full Access</h3>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="full-access" id="fullaccessyes" value="yes"
                            @if (old('full-access')=="yes")
                            checked
                          @endif

                            >
                            <label class="form-check-label" for="fullaccessyes">Yes</label>
                          </div>
                          <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="full-access" id="fullaccessno" value="no"
                            @if (old('full-access')=="no")
                            checked
                          @endif
                          @if (old('full-access')===null)
                            checked
                          @endif

                          >

                            <label class="form-check-label" for="fullaccessno">No</label>
                          </div>
                          <hr>
                          <h3>Permission List</h3>
                          @foreach ($permissions as $permission )
                          <div class="custom-control custom-checkbox">
                            <input type="checkbox"
                            class="custom-control-input"
                            id="permission_{{$permission->id}}"
                            value="{{$permission->id}}"
                            name="permission[]"
                            @if( is_array(old('permission')) && in_array("$permission->id", old('permission'))    )
                            checked
                            @endif
                            >

                            <label class="custom-control-label"
                                for="permission_{{$permission->id}}">
                                {{ $permission->id }}
                                -
                                {{ $permission->name }}
                                <em>( {{ $permission->description }} )</em>
                        </label>
                          </div>
                          @endforeach
                          <hr>
                          <input class="btn btn-primary" type="submit" value="Guardar"\>
                        </form>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/role/edit.blade.php
@extends('layouts.master.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Roles') }}</div>

                <div class="card-body">
                   @include('custom.message')

                        <form action="{{ route('role.update', $role->id)}}" method="POST">
                         @method('Put')
                          @csrf
                        <div class="container">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="name" placeholder="Name" name="name"   value={{old('name', $role->name)}}>
                              </div>
                              <div class="mb-3">
                                <input type="text" class="form-control" id="slug" placeholder="Slug" name="slug" value={{old('slug', $role->slug)}}>
                              </div>
                              <div class="form-floating">
                                <textarea class="form-control" placeholder="Description" id="description" name="description" style="height: 100px" >{{ old('description', $role->description)}}</textarea>
                              </div>
                        </div>
                        <hr>
                        <h3>Full Access</h3>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="full-access" id="fullaccessyes" value="yes"
                            @if ( $role['full-access']=="yes")
                            checked
                          @elseif (old('full-access')=="yes")
                            checked
                          @endif

                            >
                            <label class="form-check-label" for="fullaccessyes">Yes</label>
                          </div>
                          <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="full-access" id="fullaccessno" value="no"
                            @if ( $role['full-access']=="no")
                              checked
                            @elseif (old('full-access')=="no")
                              checked
                            @endif


                          >

                            <label class="form-check-label" for="fullaccessno">No</label>
                          </div>
                          <hr>
                          <h3>Permission List</h3>
                          @foreach ($permissions as $permission )
                          <div class="custom-control custom-checkbox">
                            <input type="checkbox"
                            class="custom-control-input"
                            id="permission_{{$permission->id}}"
                            value="{{$permission->id}}"
                            name="permission[]"
                            @if( is_array(old('permission')) && in_array("$permission->id", old('permission'))    )
                            checked

                            @elseif( is_array($permission_role) && in_array("$permission->id", $permission_role)    )
                            checked

                            @endif
                            >

                            <label class="custom-control-label"
                                for="permission_{{$permission->id}}">
                                {{ $permission->id }}
                                -
                                {{ $permission->name }}
                                <em>( {{ $permission->description }} )</em>
                        </label>
                          </div>
                          @endforeach
                          <hr>
                          <input class="btn btn-primary" type="submit" value="Guardar"\>
                        </form>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/role/index.blade.php
@extends('layouts.master.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Lista de Roles') }}</div>
                <div class="card-body">
                <a class= "btn btn-primary float-right" href="{{route('role.create')}}">Create</a>
                <br><br>
                @include('custom.message')
                    <table class="table table-hover">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Slug</th>
                                <th scope="col">Description</th>
                                <th scope="col">full-access</th>
                                <th colspan="3"></th>
                              </tr>
                            </thead>
                            <tbody>

                                @foreach ($roles as $role )
                                <tr>
                                <th scope="row">{{$role->id}}</th>
                                <td>{{$role->name}}</td>
                                <td>{{$role->slug}}</td>
                                <td>{{$role->description}}</td>
                                <td>{{$role['full-access']}}</td>
                                <td> <a class="btn btn-info" href="{{ route('role.show', $role->id)}}">Show</a></td>
                                <td> <a class="btn btn-success"  href="{{ route('role.edit', $role->id)}}">Edit</a></td>

                                <td>
                                    <form action="{{ route('role.destroy',$role->id)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Esta seguro que desea eliminar Rol {{$role->name}}')" class="btn btn-danger">Delete</button>
                                      </form>
                                </td>
                                </tr>
                                @endforeach
                            </tbody>
                      </table>

                      {{ $roles->onEachSide(2)->links() }}


                </div>

            </div>

        </div>

    </div>

</div>


@endsection

resources/views/role/view.blade.php
@extends('layouts.master.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h2>Edit Role</h2></div>

                <div class="card-body">
                   @include('custom.message')

                    <form action="{{ route('role.update', $role->id)}}" method="POST">
                     @csrf
                     @method('PUT')

                     <div class="container">

                        <h3>Required data</h3>

                         <div class="form-group">
                            <input type="text" class="form-control"
                            id="name"
                            placeholder="Name"
                            name="name"
                            value="{{ old('name', $role->name)}}"
                            readonly>
                          </div>
                          <div class="form-group">
                            <input type="text"
                            class="form-control"
                            id="slug"
                            placeholder="Slug"
                            name="slug"
                            value="{{ old('slug' , $role->slug)}}"
                            readonly>
                          </div>

                          <div class="form-group">

                            <textarea  readonly class="form-control" placeholder="Description" name="description" id="description" rows="3">{{old('description', $role->description)}}</textarea>
                          </div>

                          <hr>

                          <h3>Full Access</h3>
                          <div class="custom-control custom-radio custom-control-inline">
                            <input disabled type="radio" id="fullaccessyes" name="full-access" class="custom-control-input" value="yes"
                            @if ( $role['full-access']=="yes")
                              checked
                            @elseif (old('full-access')=="yes")
                              checked
                            @endif
                              >
                            <label class="custom-control-label" for="fullaccessyes">Yes</label>
                          </div>
                          <div class="custom-control custom-radio custom-control-inline">
                            <input disabled type="radio" id="fullaccessno" name="full-access" class="custom-control-input" value="no"

                            @if ( $role['full-access']=="no")
                              checked
                            @elseif (old('full-access')=="no")
                              checked
                            @endif
                              >
                            <label class="custom-control-label" for="fullaccessno">No</label>
                          </div>
                          <hr>
                          <h3>Permission List</h3>
                          @foreach($permissions as $permission)
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox"
                            disabled
                            class="custom-control-input"
                            id="permission_{{$permission->id}}"
                            value="{{$permission->id}}"
                            name="permission[]"
                            @if( is_array(old('permission')) && in_array("$permission->id", old('permission'))    )
                            checked
                            @elseif( is_array($permission_role) && in_array("$permission->id", $permission_role)    )
                            checked
                            @endif
                            >
                            <label class="custom-control-label"
                                for="permission_{{$permission->id}}">
                                {{ $permission->id }}
                                -
                                {{ $permission->name }}
                                <em>( {{ $permission->description }} )</em>
                                                        </label>
                          </div>
                          @endforeach
                          <hr>
                                                    <a class="btn btn-success" href="{{route('role.edit',$role->id)}}">Edit</a>
                          <a class="btn btn-danger" href="{{route('role.index')}}">Back</a>
                     </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection