routes/web.php
<?php

use App\Models\Role;


use App\Models\User;  //libre
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Mail\ContactanosMailable;   //libre
use Illuminate\Support\Facades\Gate; //libre
use App\Http\Controllers\Admin\RolController;
use Illuminate\Support\Facades\Mail;  //libre
use Illuminate\Support\Facades\Auth;// liberia
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Admin\TallaController;
use App\Http\Controllers\Admin\ImagenController;
use App\Http\Controllers\Admin\OfertaController;
use App\Http\Controllers\Admin\OrigenController;
use App\Http\Controllers\Cliente\CartController;
use App\Http\Controllers\Admin\SeccionController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Admin\ArticuloController;
use App\Http\Controllers\Admin\ProductoController;
use App\Http\Controllers\Cliente\BuscarController;
use App\Http\Controllers\Cliente\PerfilController;
use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\PublicadoController;
use App\Http\Controllers\Cliente\DetalleController;
use App\Http\Controllers\Admin\TallaComboController;
use App\Http\Controllers\Cliente\AccionesController;
use App\Http\Controllers\Cliente\CatalogoController;
use App\Http\Controllers\Cliente\CheckoutController;
use App\Http\Controllers\Admin\MetodoAdminController;
use App\Http\Controllers\Admin\CrearUsuarioController;
use App\Http\Controllers\Admin\UserController; //libre
use App\Http\Controllers\HomeUserController;   //libre
use App\Http\Controllers\Admin\HomeController;  //libre
use App\Http\Controllers\Admin\Reporte_UsuatioController;
use App\Http\Controllers\Cliente\CorreoFacturaController;
use App\Http\Controllers\Cliente\MetodoClienteController;
use App\Http\Controllers\Cliente\OfertaDetalleController;
use App\Http\Controllers\Admin\Relaccion_ImagenController;
use App\Http\Controllers\Admin\ValidarPagoAdminController;
use App\Http\Controllers\Cliente\FacturaClienteController;
use App\Http\Controllers\Cliente\SinAuthController;
use App\Http\Controllers\Logistica\MetodoLogisticaController;
use App\Http\Controllers\Cliente\ValidarPagoClienteController;
use App\Http\Controllers\Repartidor\MetodoRepartidorController;
use App\Http\Controllers\Logistica\EntregarPedidoLogisticaController;
use App\Http\Controllers\Repartidor\EntregarPedidosMensajeroController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    //Ofertas


    $products=DB::table('productos')
    ->where('imagens.perfil','si')
    ->where('ofertas.estado','1')
    ->select(
        'productos.codigo_producto',
        'productos.id',
        'relaccion__imagens.relaccion_id',
        'productos.stock',
        'productos.estado',
        'ofertas.precio_oferta',
        'productos.descripcion',
        'imagens.url as imagen',
        'articulos.descripcion as articulo',
        'categorias.descripcion as categoria',
        'productos.created_at',
        'imagens.perfil',
        'imagens.url'
    )
    ->join('ofertas', 'productos.id', '=', 'ofertas.producto_id')
    ->join('publicados', 'productos.id', '=', 'publicados.producto_id')
    ->join('relaccions', 'productos.relaccion_id', '=', 'relaccions.id')
    ->join('articulos', 'relaccions.articulo_id', '=', 'articulos.id')
    ->join('categorias', 'relaccions.categoria_id', '=', 'categorias.id')
    ->join('relaccion__imagens', 'relaccions.id', '=', 'relaccion__imagens.relaccion_id')
    ->join('imagens', 'relaccion__imagens.imagen_id', '=', 'imagens.id')
    ->get();



  //  return $products;

    return view('welcome')->with(['products' =>$products]);
});


Route::get('/cart', [CartController::class, 'cart'])->name('cart.index');
Route::post('/add', [CartController::class, 'add'])->name('cart.store');
Route::post('/update', [CartController::class, 'update'])->name('cart.update');
Route::post('/remove', [CartController::class, 'remove'])->name('cart.remove');
Route::post('/clear', [CartController::class, 'clear'])->name('cart.clear');

Auth::routes(['verify' =>true]);



Route::post('/combo', [TallaComboController::class, 'consultaTallas']);
Route::get('/estadouser/{id}/{state}/{name}', [TallaComboController::class, 'usuarioEstado']);
Route::get('/estadocategoria/{id}/{estado}/{descripcion}', [TallaComboController::class, 'categoriaEstado']);
Route::get('/estadocolor/{id}/{estado}/{descripcion}', [TallaComboController::class, 'colorEstado']);
Route::get('/estadoseccion/{id}/{estado}/{descripcion}', [TallaComboController::class, 'seccionEstado']);
Route::get('/estadotalla/{id}/{estado}/{talla}', [TallaComboController::class, 'tallaEstado']);
Route::get('/estadoorigen/{id}/{estado}/{descripcion}', [TallaComboController::class, 'origenEstado']);
Route::get('/publicar/{producto_id}/{relaccion_id}', [TallaComboController::class, 'publicarProducto']);
Route::get('/publicarestado/{id}/{estado}', [TallaComboController::class, 'estadoPublicado']);
Route::get('/ofertar/{producto_id}/{publicado_id}', [TallaComboController::class, 'ofertarProducto']);
Route::get('/ofertaestado/{id}/{estado}', [TallaComboController::class, 'estadoOferta']);
Route::get('/eliminaroferta/{id}/{idpublicado}', [TallaComboController::class, 'eliminarOferta']);




Route::get('/tienda', [HomeUserController::class, 'getUser'])->name('tienda');
Route::post('/combocatalogo', [HomeUserController::class, 'catalogo'])->name('combocatalogo');

/*
Route::get('/contactanos', function () {
    $correo = new ContactanosMailable;
    Mail::to('bacoth@gmail.com')->send($correo);

    return "Mensaje enviado";
});
*/

//Route::get('/enviar/factura',[CorreoFacturaController::class, 'envioFactura'])->name('envio.factura');


Route::resource('/role', RoleController::class)->names('role');


//Route::get('/cliente/perfil',[ RegisterController::class, 'actualizar'])->name('cliente-perfil');


Route::get('/test', function () {

	return Role::create([
        'rol' => 'Logistica',
        'slug' => 'logistica',
        'description' =>'Entregar productos',
        'full-access' =>'no'
        ]);

    });


// Google login
Route::get('login/google', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGoogle'])->name('login.google');
Route::get('login/google/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGoogleCallback']);

// FaceBook login
Route::get('login/facebook', [App\Http\Controllers\Auth\LoginController::class, 'redirectToFacebook'])->name('login.facebook');
Route::get('login/facebook/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleFacebookCallback']);

// GitHub login
Route::get('login/github', [App\Http\Controllers\Auth\LoginController::class, 'redirectToGithub'])->name('login.github');
Route::get('login/github/callback', [App\Http\Controllers\Auth\LoginController::class, 'handleGithubCallback']);


//Controlladores para Admin
Route::prefix('/administrador')->group(function (){
    Route::resource('/perfil', UserController::class)->names('perfil');
    Route::resource('/modulo_producto/producto', ProductoController::class)->names('producto');
    Route::resource('/modulo_producto/gestion/color', ColorController::class)->names('color');
    Route::resource('/modulo_producto/gestion/categoria', CategoriaController::class)->names('categoria');
    Route::resource('/modulo_producto/gestion/seccion', SeccionController::class)->names('seccion');
    Route::resource('/modulo_producto/gestion/talla', TallaController::class)->names('talla');
    Route::resource('/modulo_producto/gestion/origen', OrigenController::class)->names('origen');
    Route::resource('/modulo_producto/gestion/articulo', ArticuloController::class)->names('articulo');
    Route::resource('/modulo_producto/publicado/publicado', PublicadoController::class)->names('publicado');
    Route::resource('/modulo_producto/publicado/oferta', OfertaController::class)->names('oferta');
    Route::resource('/modulo_producto/producto/imagen', ImagenController::class)->names('imagen');
    Route::resource('/modulo_producto/producto/relaccion_imagen', Relaccion_ImagenController::class)->names('relaccion_imagen');
    Route::get('modulo_usuario/reporte_usuario',[Reporte_UsuatioController::class, 'reporteUsuario'])->name('reporte_usuario');
    Route::get('modulo_usuario/reporte_cliente',[Reporte_UsuatioController::class, 'reporteCliente'])->name('reporte_cliente');
    Route::resource('/modulo_usuario/rol', RolController::class)->names('asignarRol');
    Route::resource('/modulo_usuario/crear', CrearUsuarioController::class)->names('crearusuario');
    Route::get('/panel',[HomeController::class,'index'])->name('home');
    Route::resource('/facturacion/validar/pago', ValidarPagoAdminController::class)->names('validar.pago.admin');
    Route::get('/pago/rechazado/{id}', [MetodoAdminController::class, 'rechazadoPago']);
    Route::get('/pago/factura/detalle/{id}', [MetodoAdminController::class, 'detalleFacturaAdmin']);
    Route::get('/facturacion/generar/factura', [MetodoAdminController::class, 'facturaPendiente']);
    Route::get('/facturacion/factura/autorizado', [MetodoAdminController::class, 'facturaAutorizado']);
    Route::get('/facturacion/factura/rechazado', [MetodoAdminController::class, 'facturaRechazado']);
    Route::get('/facturacion/factura/facturaPDF/{id}', [MetodoAdminController::class, 'descargarPDF']);
    Route::get('/reportes/entregas', [MetodoAdminController::class, 'reporteEntregas']);
    Route::get('/facturacion/generar/factura/{id}', [MetodoAdminController::class, 'generarNumerador']);

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    use HasFactory;
    protected $primaryKey = 'id';
    protected $table = 'colors';
    protected $fillable = [
        'descripcion',
        'estado',

    ];

    public function relaciones()
    {
        return $this->hasMany(Relaccion::class);
    }
}

app/Http/Controllers/Admin/ColorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Color;
use App\Models\Estado;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ColorController extends Controller
{


   /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth','verified']);
        $this->middleware('administrador',['only'=>['index', 'create', 'store', 'show', 'update', 'destroy']]);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $colors =  Color::get();
        // $roles = Role::get();
       return view('page/admin/color/index',compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$estados=Estado::get();
        return view('page/admin/color/crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'descripcion'          => 'required|max:50|',
            'estado'   => 'required|in:1,2'
        ]);

        Color::create($request->all());
        return redirect()->route('color.index')
        ->with('status_success','Color guardado con éxito ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Color $color)
    {
        $colors="dd";
       // return view('page/admin/color/mostrar',compact('color'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color)
    {

        return view('page/admin/color/editar',compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Color $color)
    {
        $request->validate([
            'descripcion'          => 'required|max:50|',
            'estado'   => 'required|in:1,2'
        ]);

        $color->update($request->all());
        return redirect()->route('color.index')
        ->with('status_success','Color actualizado con éxito ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Color $color)
    {
        $color->delete();
        return redirect()->route('color.index')
        ->with('status_success','Color sé eliminó  con éxito ');
    }
}

resources/views/page/admin/color/crear.blade.php
@extends('adminlte::page')
@section('title', 'Administrador || Productos Crear Color')
@section('plugins.Sweetalert2', true)

@section('content')

<div class="card">
    <div class="card-header">
        <div class="row">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Administrador</li>
                        <li class="breadcrumb-item">Productos</li>
                        <li class="breadcrumb-item">Gestión Producto</li>
                        <li class="breadcrumb-item">Color</li>
                        <li class="breadcrumb-item active" aria-current="page"><a href="{{ url()->previous() }}">Back</a></li>

                    </ol>
                </nav>

        </div>
    </div>
    <div class="card-body">
        @include('custom.message')

             <form action="{{ route('color.store')}}" method="POST">
             @csrf
             <div class="container">
                 <div class="mb-3">
                     <input type="text" class="form-control" id="descripcion" placeholder="Color" name="descripcion"   value={{old('descripcion')}}>
                   </div>

             </div>
             <hr>
             <h3>Estado</h3>
             <div class="form-check form-check-inline">
                 <input class="form-check-input" type="radio" name="estado" id="activo" value="1"
                 @if (old('estado')=="activo")
                 checked
               @endif

                 >
                 <label class="form-check-label" for="fullaccessyes">Activo</label>
               </div>
               <div class="form-check form-check-inline">
                 <input class="form-check-input" type="radio" name="estado" id="deshabilitado" value="2"
                 @if (old('estado')=="deshabilitado")
                 checked
               @endif
               @if (old('estado')===null)
                 checked
               @endif

               >

                 <label class="form-check-label" for="fullaccessno">Inactivo</label>
               </div>
               <hr>


               <hr>
               <input class="btn btn-primary" type="submit" value="Guardar"\>
             </form>



     </div>
</div>

@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link  rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
    <link  rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
    <link  rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css">

@endsection

@section('js')

@stop

resources/views/page/admin/color/editar.blade.php
@extends('adminlte::page')
@section('title', 'Gestión Color || Editar')
@section('plugins.Sweetalert2', true)
@section('content')

<div class="card">
    <div class="card-header">
    <h1 class="card-title">Gestión Color</h1>
    </div>
    <div class="card-body">
        @include('custom.message')

             <form action="{{ route('color.update', $color->id)}}" method="POST">
              @method('Put')
               @csrf
             <div class="container">
                 <div class="mb-3">
                     <input type="text" class="form-control" id="descripcion" placeholder="Color" name="descripcion"   value={{old('descripcion', $color->descripcion)}}>

                   </div>

             </div>
             <hr>
             <h3>Estado</h3>
             <div class="form-check form-check-inline">
                 <input class="form-check-input" type="radio" name="estado" id="activo" value="activo"
                 @if ( $color['estado']=="activo")
                 checked
               @elseif (old('estado')=="activo")
                 checked
               @endif

                 >
                 <label class="form-check-label" for="fullaccessyes">Activo</label>
               </div>
               <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="estado" id="deshabilitado" value="deshabilitado"
                 @if ( $color['estado']=="deshabilitado")
                   checked
                 @elseif (old('estado')=="deshabilitado")
                   checked
                 @endif


               >

                 <label class="form-check-label" for="fullaccessno">Deshabilitado</label>
               </div>
               <hr>
               <hr>
               <input class="btn btn-primary" type="submit" value="Guardar"\>
             </form>
     </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <link  rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
    <link  rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
    <link  rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css">

@endsection

@section('js')

@stop

resources/views/page/admin/color/index.blade.php
@extends('adminlte::page')
@section('title', 'Administrador || Productos Gestion Color')

@section('plugins.Sweetalert2', true)


@section('css')
    <link  rel="stylesheet" href="/css/admin_custom.css">
    <link  rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
    <link  rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
    <link  rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap4.min.css">

@endsection

@section('content')

 <div class="card">
    <div class="card-header">
        <div class="row">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Administrador</li>
                        <li class="breadcrumb-item">Productos</li>
                        <li class="breadcrumb-item">Gestión Producto</li>
                        <li class="breadcrumb-item">Color</li>

                    </ol>
                </nav>

        </div>
    </div>
    <div class="card-body">
        @include('custom.message')
       <a href=" {{route('color.create')}}" class="btn btn-primary">CREAR</a>
    <hr>


       <table  class="table table-striped" id="colores">
        <thead>
            <tr>
                <th scope="col">Cod</th>
                <th scope="col">Nombre</th>
                <th scope="col">Creado</th>
                <th scope="col">Actualizado</th>
                <th scope="col">Estado</th>
                  <!--
                <th>ELIMINAR</th>
                -->

            </tr>
        </thead>
        <tbody>
            @foreach ($colors as $color )
            <tr>
                <td scope="row">{{$color->id}}</td>
                <td>{{$color->descripcion}}</td>
                <td>{{$color->created_at->diffForHumans()}}</td>
                <td>{{$color->updated_at->diffForHumans()}}</td>

                @if ($color->estado =="1")
                <td>
                    <a class="btn btn-outline-success"  href="{{ url('/estadocolor', ['id' => $color->id, 'estado' => $color->estado , 'descripcion' => $color->descripcion])}}">Activo</a>
                </td>
                @else
                <td>
                    <a class="btn btn-outline-danger"  href="{{ url('/estadocolor', ['id' => $color->id, 'estado' => $color->estado , 'descripcion' => $color->descripcion])}}">Inactivo</a>
                </td>
                @endif


                <!--
                <td>
                    <form action="{{ route('color.destroy',$color->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button onclick="return confirm('Esta seguro que desea eliminar Color :  {{$color->descripcion}}')" class="btn btn-danger">Eliminar</button>
                    </form>
                </td>
            -->

                                </tr>

            @endforeach
        </tbody>
       </table>

    </div>
  </div>
@endsection

@section('js')

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/responsive.bootstrap4.min.js"></script>
<script>
     $('#colores').DataTable({
         responsive:true,
         autoWidth: false,

         "language": {
           // "lengthMenu": "Mostrar _MENU_ registros por página",
           "lengthMenu": "Mostrar "+
           `<select>
           <option value='3'>3</option>
           <option value='25'>25</option>
           <option value='50'>50</option>
           <option value='100'>100</option>
           <option value='-1'>all</option>
           </select> `  +
           "registros por página",
            "zeroRecords": "No se encontró nada,  - lo siento",
            "info": "Mostrando página _PAGE_ de _PAGES_",
            "infoEmpty": "No hay registros disponibles",
            "infoFiltered": "(filtrado de _MAX_ registros totales)",
            'search':'Buscar:',
            'paginate':{
                'next':'Siguiente',
                'previous':'Anterior'
            }
        }
     });
</script>
@endsection

resources/views/page/admin/color/mostrar.blade.php
@extends('adminlte::page')
@section('title', 'Color')

@section('plugins.Sweetalert2', true)
@section('content_header')
<h1>Tablero</>
@stop

@section('content')

<div class="card">
    <div class="card-header">
    <h1 class="card-title">Hola mundo</h1>
    </div>

    <div class="card-body">
        @include('custom.message')

         <form action="{{ route('color.update', $color->id)}}" method="POST">
          @csrf
          @method('PUT')

          <div class="container">

             <h3>Required data</h3>

              <div class="form-group">
                 <input type="text" class="form-control"
                 id="name"
                 placeholder="Name"
                 name="name"
                 value="{{ old('name', $color->descripcion)}}"
                 readonly>
               </div>
               <div class="form-group">
                 <input type="text"
                 class="form-control"
                 id="slug"
                 placeholder="Slug"
                 name="slug"
                 value="{{ old('slug' , $color->estado)}}"
                 readonly>
               </div>
               <div class="form-group">
                <input type="text"
                class="form-control"
                id="created_at"
                placeholder="Fecha"
                name="created_at"
                value="{{ old('created_at' , $color->created_at)}}"
                readonly>
              </div>

              <div class="form-group">
                <input type="text"
                class="form-control"
                id="updated_at"
                placeholder="Fecha"
                name="updated_at"
                value="{{ old('updated_at' , $color->updated_at)}}"
                readonly>
              </div>


               <hr>




                <a class="btn btn-success" href="{{route('color.edit',$color->id)}}">Edit</a>
               <a class="btn btn-danger" href="{{route('color.index')}}">Back</a>
          </div>
         </form>
     </div>

</div>

@stop

@section('css')
	<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop